---@class vk.RawEnums
local vk = {}

---@enum vk.ApiVersion
vk.ApiVersion = {
	V1_0 = 0x00400000,
	V1_1 = 0x00401000,
	V1_2 = 0x00402000,
}

---@enum vk.PhysicalDeviceType
vk.PhysicalDeviceType = {
	OTHER = 0,
	INTEGRATED_GPU = 1,
	DISCRETE_GPU = 2,
	VIRTUAL_GPU = 3,
	CPU = 4,
}

---@enum vk.ImageLayout
vk.ImageLayout = {
	UNDEFINED = 0,
	GENERAL = 1,
	COLOR_ATTACHMENT_OPTIMAL = 2,
	DEPTH_STENCIL_ATTACHMENT_OPTIMAL = 3,
	DEPTH_STENCIL_READ_ONLY_OPTIMAL = 4,
	SHADER_READ_ONLY_OPTIMAL = 5,
	TRANSFER_SRC_OPTIMAL = 6,
	TRANSFER_DST_OPTIMAL = 7,
	PREINITIALIZED = 8,
}

---@enum vk.ImageType
vk.ImageType = {
	TYPE_1D = 0,
	TYPE_2D = 1,
	TYPE_3D = 2,
}

---@enum vk.BufferUsage
vk.BufferUsage = {
	TRANSFER_SRC = 0x00000001,
	TRANSFER_DST = 0x00000002,
	UNIFORM_TEXEL_BUFFER = 0x00000004,
	STORAGE_TEXEL_BUFFER = 0x00000008,
	UNIFORM_BUFFER = 0x00000010,
	STORAGE_BUFFER = 0x00000020,
	INDEX_BUFFER = 0x00000040,
	VERTEX_BUFFER = 0x00000080,
	INDIRECT_BUFFER = 0x00000100,
}

---@enum vk.SharingMode
vk.SharingMode = {
	EXCLUSIVE = 0,
	CONCURRENT = 1,
}

---@enum vk.PipelineBindPoint
vk.PipelineBindPoint = {
	GRAPHICS = 0,
	COMPUTE = 1,
}

---@enum vk.SubpassContents
vk.SubpassContents = {
	INLINE = 0,
	SECONDARY_COMMAND_BUFFERS = 1,
}

---@enum vk.CommandBufferLevel
vk.CommandBufferLevel = {
	PRIMARY = 0,
	SECONDARY = 1,
}

---@enum vk.QueueFlagBits
vk.QueueFlagBits = {
	GRAPHICS = 0x00000001,
	COMPUTE = 0x00000002,
	TRANSFER = 0x00000004,
}

---@enum vk.CommandPoolCreateFlagBits
vk.CommandPoolCreateFlagBits = {
	TRANSIENT = 0x00000001,
	RESET_COMMAND_BUFFER = 0x00000002,
}

---@enum vk.StructureType
vk.StructureType = {
	APPLICATION_INFO = 0,
	INSTANCE_CREATE_INFO = 1,
	DEVICE_QUEUE_CREATE_INFO = 2,
	DEVICE_CREATE_INFO = 3,
	SUBMIT_INFO = 4,
	MEMORY_ALLOCATE_INFO = 5,
	MAPPED_MEMORY_RANGE = 6,
	BIND_SPARSE_INFO = 7,
	FENCE_CREATE_INFO = 8,
	SEMAPHORE_CREATE_INFO = 9,
	EVENT_CREATE_INFO = 10,
	QUERY_POOL_CREATE_INFO = 11,
	BUFFER_CREATE_INFO = 12,
	BUFFER_VIEW_CREATE_INFO = 13,
	IMAGE_CREATE_INFO = 14,
	IMAGE_VIEW_CREATE_INFO = 15,
	SHADER_MODULE_CREATE_INFO = 16,
	PIPELINE_CACHE_CREATE_INFO = 17,
	PIPELINE_SHADER_STAGE_CREATE_INFO = 18,
	PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO = 19,
	PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO = 20,
	PIPELINE_TESSELLATION_STATE_CREATE_INFO = 21,
	PIPELINE_VIEWPORT_STATE_CREATE_INFO = 22,
	PIPELINE_RASTERIZATION_STATE_CREATE_INFO = 23,
	PIPELINE_MULTISAMPLE_STATE_CREATE_INFO = 24,
	PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO = 25,
	PIPELINE_COLOR_BLEND_STATE_CREATE_INFO = 26,
	PIPELINE_DYNAMIC_STATE_CREATE_INFO = 27,
	GRAPHICS_PIPELINE_CREATE_INFO = 28,
	COMPUTE_PIPELINE_CREATE_INFO = 29,
	PIPELINE_LAYOUT_CREATE_INFO = 30,
	SAMPLER_CREATE_INFO = 31,
	DESCRIPTOR_SET_LAYOUT_CREATE_INFO = 32,
	DESCRIPTOR_POOL_CREATE_INFO = 33,
	DESCRIPTOR_SET_ALLOCATE_INFO = 34,
	WRITE_DESCRIPTOR_SET = 35,
	COPY_DESCRIPTOR_SET = 36,
	FRAMEBUFFER_CREATE_INFO = 37,
	RENDER_PASS_CREATE_INFO = 38,
	COMMAND_POOL_CREATE_INFO = 39,
	COMMAND_BUFFER_ALLOCATE_INFO = 40,
	COMMAND_BUFFER_INHERITANCE_INFO = 41,
	COMMAND_BUFFER_BEGIN_INFO = 42,
	RENDER_PASS_BEGIN_INFO = 43,
	BUFFER_MEMORY_BARRIER = 44,
	IMAGE_MEMORY_BARRIER = 45,
	MEMORY_BARRIER = 46,
	LOADER_INSTANCE_CREATE_INFO = 47,
	LOADER_DEVICE_CREATE_INFO = 48,

	-- VK_KHR_swapchain
	SWAPCHAIN_CREATE_INFO_KHR = 1000001000,
	PRESENT_INFO_KHR = 1000001001,
}

return vk
